HOTEL_TESTE = 'Pousado Remanso'
CIDADE_TESTE = 'Bonito'
ITEM_PASSEIO_GRUTA = 'Gruta do Lago Azul'
ITEM_PASSEIO_PARQUE = 'Parque das Cachoeiras'
PASSEIOS_TESTE = f'{ITEM_PASSEIO_GRUTA},{ITEM_PASSEIO_PARQUE}'
LISTA_PASSEIOS = PASSEIOS_TESTE.split(',')
DIAS_PASSEIO = ['qui', 'ter']
HOSPEDE_TESTE = 'Ana Conda' # https://www.anaconda.com/  :))
FORMATO_RETORNO_CONSUMO = '{} > {}.'